import React from 'react';
import {
  LuPencil,
  LuTerminal,
  LuUsers,
  LuCpu,
  LuUserPlus,
  LuPuzzle,
  LuActivity,
  LuBot,
  LuCode,
  LuSettings,
  LuGitBranch,
  LuSearch,
  LuShoppingBag,
  LuShoppingCart,
  LuLock,
  LuGlobe,
  LuPalette,
  LuZap,
  LuBug,
  LuMonitor,
  LuTriangleAlert,
  LuFlag,
  LuCirclePlay,
  LuHardDrive,
  LuShield,
  LuFileText,
  LuFileCode,
  LuFolderOpen,
  LuFolder,
  LuPlus,
  LuX,
  LuBox,
  LuCheck,
  LuCircleCheck,
  LuCircleX,
  LuCircle,
  LuStar,
  LuRefreshCw,
  LuMessageCircle,
  LuWifi,
  LuChartBar,
  LuLink,
  LuGitCompare,
  LuTrash2,
  LuMapPin,
  LuBook,
  LuMenu,
  LuLayers,
  LuServer,
  LuCloud,
  LuTarget,
  LuInfo,
  LuKey,
  LuDatabase,
  LuPlay,
  LuPause,
  LuSkipForward,
  LuHeart,
} from 'react-icons/lu';

export type IconName =
  | 'edit3' | 'edit' | 'terminal' | 'users' | 'cpu' | 'userPlus'
  | 'puzzle' | 'activity' | 'bot' | 'code' | 'settings' | 'gitBranch'
  | 'gitCompare' | 'search' | 'shoppingBag' | 'shopping-cart' | 'lock' | 'globe'
  | 'palette' | 'zap' | 'bug' | 'monitor' | 'alertTriangle' | 'alert-triangle'
  | 'flag' | 'playCircle' | 'play-circle' | 'hardDrive' | 'shield'
  | 'fileText' | 'file-text' | 'fileCode' | 'file-code'
  | 'folderOpen' | 'folder-open' | 'folder' | 'plus' | 'x' | 'box'
  | 'check' | 'checkCircle' | 'check-circle' | 'xCircle' | 'x-circle' | 'circle'
  | 'star' | 'refreshCw' | 'refresh-cw' | 'messageCircle' | 'message-circle'
  | 'wifi' | 'barChart2' | 'bar-chart-2' | 'link'
  | 'trash' | 'mapPin' | 'map-pin' | 'book' | 'menu' | 'layers'
  | 'server' | 'cloud' | 'target' | 'info' | 'key' | 'database'
  | 'play' | 'pause' | 'skipForward' | 'skip-forward' | 'heart';

const iconMap: Record<string, React.ComponentType<any>> = {
  edit3: LuPencil,
  edit: LuPencil,
  terminal: LuTerminal,
  users: LuUsers,
  cpu: LuCpu,
  userPlus: LuUserPlus,
  puzzle: LuPuzzle,
  activity: LuActivity,
  bot: LuBot,
  code: LuCode,
  settings: LuSettings,
  gitBranch: LuGitBranch,
  gitCompare: LuGitCompare,
  search: LuSearch,
  shoppingBag: LuShoppingBag,
  'shopping-cart': LuShoppingCart,
  lock: LuLock,
  globe: LuGlobe,
  palette: LuPalette,
  zap: LuZap,
  bug: LuBug,
  monitor: LuMonitor,
  alertTriangle: LuTriangleAlert,
  'alert-triangle': LuTriangleAlert,
  flag: LuFlag,
  playCircle: LuCirclePlay,
  'play-circle': LuCirclePlay,
  hardDrive: LuHardDrive,
  shield: LuShield,
  fileText: LuFileText,
  'file-text': LuFileText,
  fileCode: LuFileCode,
  'file-code': LuFileCode,
  folderOpen: LuFolderOpen,
  'folder-open': LuFolderOpen,
  folder: LuFolder,
  plus: LuPlus,
  x: LuX,
  box: LuBox,
  check: LuCheck,
  checkCircle: LuCircleCheck,
  'check-circle': LuCircleCheck,
  xCircle: LuCircleX,
  'x-circle': LuCircleX,
  circle: LuCircle,
  star: LuStar,
  refreshCw: LuRefreshCw,
  'refresh-cw': LuRefreshCw,
  messageCircle: LuMessageCircle,
  'message-circle': LuMessageCircle,
  wifi: LuWifi,
  barChart2: LuChartBar,
  'bar-chart-2': LuChartBar,
  link: LuLink,
  trash: LuTrash2,
  mapPin: LuMapPin,
  'map-pin': LuMapPin,
  book: LuBook,
  menu: LuMenu,
  layers: LuLayers,
  server: LuServer,
  cloud: LuCloud,
  target: LuTarget,
  info: LuInfo,
  key: LuKey,
  database: LuDatabase,
  play: LuPlay,
  pause: LuPause,
  skipForward: LuSkipForward,
  'skip-forward': LuSkipForward,
  heart: LuHeart,
};

export function getIconComponent(name: IconName): React.ComponentType<any> {
  return iconMap[name] || LuInfo;
}

export const iconNames = Object.keys(iconMap) as IconName[];
