import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import * as path from 'path';
import { AgentStudioEngine } from '@autonomous-lifecycle-protocol-alp/parser';

const CLI = path.resolve(process.cwd(), 'cli/dist/index.js');

describe('ALP Agent Studio', () => {
  describe('AgentStudioEngine', () => {
    it('creates a blank project with correct initial metadata', () => {
      const engine = new AgentStudioEngine();
      const project = engine.createProject('Test Project', undefined, 'Custom test project');

      expect(project.projectId).toMatch(/^proj-/);
      expect(project.name).toBe('Test Project');
      expect(project.description).toBe('Custom test project');
      expect(project.nodes).toHaveLength(0);
      expect(project.edges).toHaveLength(0);
      expect(project.version).toBe('1.0.0');
    });

    it('creates a project from a pre-built template with nodes and edges', () => {
      const engine = new AgentStudioEngine();
      const project = engine.createProject('Coder Swarm', 'tpl-coder');

      expect(project.template).toBe('tpl-coder');
      expect(project.nodes.length).toBeGreaterThan(0);
      expect(project.edges.length).toBeGreaterThan(0);

      const agentNode = project.nodes.find(n => n.type === 'AGENT');
      expect(agentNode).toBeDefined();
    });

    it('adds nodes and connects edges dynamically', () => {
      const engine = new AgentStudioEngine();
      const project = engine.createProject('Dynamic Pipeline');

      const nodeA = engine.addNode(project.projectId, 'AGENT', 'Ingest Agent', { x: 100, y: 100 });
      const nodeB = engine.addNode(project.projectId, 'TASK', 'Process Batch', { x: 300, y: 100 });
      const nodeC = engine.addNode(project.projectId, 'GATE', 'Quality Gate', { x: 500, y: 100 });

      expect(nodeA.type).toBe('AGENT');
      expect(nodeB.type).toBe('TASK');
      expect(nodeC.type).toBe('GATE');

      const edge1 = engine.addEdge(project.projectId, nodeA.id, nodeB.id, 'data');
      const edge2 = engine.addEdge(project.projectId, nodeB.id, nodeC.id, 'check');

      expect(edge1.from).toBe(nodeA.id);
      expect(edge1.to).toBe(nodeB.id);
      expect(edge2.label).toBe('check');

      const updated = engine.getProject(project.projectId);
      expect(updated?.nodes).toHaveLength(3);
      expect(updated?.edges).toHaveLength(2);
    });

    it('validates a correct DAG without cycles and computes topological order', () => {
      const engine = new AgentStudioEngine();
      const project = engine.createProject('Valid DAG', 'tpl-fullstack');

      const report = engine.validateDAG(project.projectId);
      expect(report.valid).toBe(true);
      expect(report.errors).toHaveLength(0);
      expect(report.topologicalOrder.length).toBe(report.nodeCount);
    });

    it('detects cycles in an invalid DAG', () => {
      const engine = new AgentStudioEngine();
      const project = engine.createProject('Cycle Project');

      const n1 = engine.addNode(project.projectId, 'TASK', 'Step 1');
      const n2 = engine.addNode(project.projectId, 'TASK', 'Step 2');
      const n3 = engine.addNode(project.projectId, 'TASK', 'Step 3');

      engine.addEdge(project.projectId, n1.id, n2.id);
      engine.addEdge(project.projectId, n2.id, n3.id);
      engine.addEdge(project.projectId, n3.id, n1.id); // creates a cycle

      const report = engine.validateDAG(project.projectId);
      expect(report.valid).toBe(false);
      expect(report.errors.some(e => e.includes('Cycle detected'))).toBe(true);
    });

    it('exports project to ALP syntax specification', () => {
      const engine = new AgentStudioEngine();
      const project = engine.createProject('Export Test', 'tpl-coder');
      const alpSpec = engine.exportProject(project.projectId);
      expect(alpSpec).toContain('# ALP Specification — Generated by Agent Studio');
      expect(alpSpec).toContain('@agent');
      expect(alpSpec).toContain('@gate');
    });

    it('lists templates and capability listings from marketplace', () => {
      const engine = new AgentStudioEngine();
      const templates = engine.listTemplates();
      expect(templates.length).toBeGreaterThanOrEqual(4);
      expect(templates.some(t => t.templateId === 'tpl-coder')).toBe(true);

      const allCaps = engine.listCapabilities();
      expect(allCaps.length).toBeGreaterThanOrEqual(5);

      const reasoningCaps = engine.listCapabilities('reasoning');
      expect(reasoningCaps.every(c => c.category === 'reasoning')).toBe(true);
    });
  });

  describe('CLI Commands', () => {
    it('alp studio create scaffolds a new visual project', () => {
      const output = execFileSync('node', [CLI, 'studio', 'create', 'MyAgent', '--template', 'tpl-coder'], {
        encoding: 'utf-8',
        timeout: 10000,
      });

      expect(output).toContain('ALP Agent Studio — Project Created');
      expect(output).toContain('MyAgent');
      expect(output).toContain('tpl-coder');
      expect(output).toContain('Nodes:');
    });

    it('alp studio templates lists available starter templates', () => {
      const output = execFileSync('node', [CLI, 'studio', 'templates'], {
        encoding: 'utf-8',
        timeout: 10000,
      });

      expect(output).toContain('ALP Agent Studio — Built-in Templates');
      expect(output).toContain('tpl-coder');
      expect(output).toContain('tpl-fullstack');
    });

    it('alp studio capabilities displays marketplace items', () => {
      const output = execFileSync('node', [CLI, 'studio', 'capabilities'], {
        encoding: 'utf-8',
        timeout: 10000,
      });

      expect(output).toContain('ALP Agent Studio — Capability Marketplace');
      expect(output).toContain('cap-');
    });

    it('alp agent-studio validate runs topological check on projects', () => {
      const output = execFileSync('node', [CLI, 'agent-studio', 'validate', 'sample-proj'], {
        encoding: 'utf-8',
        timeout: 10000,
      });

      expect(output).toContain('DAG Validation Report');
      expect(output).toContain('Valid:      YES');
    });

    it('alp agent-studio export outputs valid ALP specification', () => {
      const output = execFileSync('node', [CLI, 'agent-studio', 'export', 'sample-proj'], {
        encoding: 'utf-8',
        timeout: 10000,
      });

      expect(output).toContain('ALP Export');
      expect(output).toContain('@agent');
    });
  });
});
