export const BLOCK_TYPES: Record<string, string> = {
  project: 'Defines the top-level project configuration, including goals, features, and metadata.',
  task: 'A unit of work that can be assigned to an agent. Has dependencies, acceptance criteria, and verification steps.',
  feature: 'A high-level product capability composed of multiple tasks.',
  workflow: 'Defines the step-by-step process agents follow (e.g., standard development lifecycle).',
  agent: 'An autonomous role with defined capabilities, permissions, and responsibilities.',
  memory: 'A piece of persistent knowledge stored across agent sessions.',
  state: 'Tracks the current state of the project, including active workflows and recent changes.',
  artifact: 'A tangible output produced by a task or workflow (e.g., a document, binary, or deployment).',
  decision: 'A recorded architectural decision with context, alternatives, and rationale.',
  constraint: 'An immutable rule that restricts how the system can evolve.',
  verification: 'A testable acceptance criterion for a task or feature.',
  dependency: 'Declares a hard or soft dependency on another object.',
  resource: 'A shared resource (API endpoint, database, service) consumed by tasks.',
  event: 'A lifecycle event emitted by the runtime or an agent.',
  goal: 'A high-level objective the project is working toward.',
  context: 'A scoped set of variables and rules available to a workflow or agent.',
  rule: 'An architectural constraint that must always be satisfied.',
  plugin: 'An extension module that adds custom object types or tool integrations.',
  policy: 'A governance rule that controls which actions are allowed, denied, or warned.',
  timeline: 'A declarative schedule for triggering events or actions using cron or one-shot triggers.',
  contract: 'A runtime boundary contract defining least-privilege access between two entities.',
  vault: 'An encrypted secrets store with recipient-scoped X25519 envelope + AES-256-GCM.',
  type: 'Declares a custom object type with custom properties and validation.',
  macro: 'A dynamic object generator that produces objects from templates.',
  repo: 'A remote Git repository used for cross-repository orchestration.',
  swarm: 'A coordinated group of agents executing tasks concurrently.',
  package: 'A distributable plugin package with versioned dependencies.',
  plan: 'A structured execution plan with ranked steps and dependencies.',
  lesson: 'A post-run self-critique record capturing what went wrong and how to improve.',
  offer: 'A negotiation offer from one agent to another with terms and constraints.',
  trace: 'A signed execution trace for end-to-end provenance tracking.',
  migration: 'A live upgrade manifest defining steps and rollback procedures for version migration.',
  workspace: 'A multi-project workspace root declaring shared config, imports, and governance policies.',
  agent_state: 'Tracks the current runtime state of an agent (status, capabilities, session context).',
  agent_override: 'Restricts a workspace agent\'s capabilities within a member project.',
  swarm_marketplace: 'Autonomous skill registry, provider discovery, invocation, rating, and cost tracking.',
  arch_decomposer: 'Analyzes a monolith and emits a microservice plan with boundaries and data contracts.',
  edge_model: 'Configuration for offline-capable edge inference models with fallback strategies.',
  cost_optimizer: 'Predictive token and execution cost reduction via prompt compression, batching, and caching.',
  identity: 'Declares an agent identity (name, keys, capabilities) for authentication and authorization.',
  negotiate: 'Agent negotiation engine for bartering resources, deadlines, and contract terms.',
  vector_store: 'Vector similarity search and semantic retrieval over embedded ALP objects.',
  sandbox_env: 'Containerized sandbox environment for safe execution of untrusted code or plugins.',
  crdt_sync: 'Distributed CRDT state synchronization across multiple nodes using LWW-Register.',
  self_healing: 'Automatic diagnosis and patch generation for syntax/schema violations and broken refs.',
  formal_verification: 'Formal verification engine using transition systems, model checking, and proof generation.',
  asset_context: 'Workspace asset linking and context binding for multi-modal content (images, video, audio).',
  cost_budget: 'Hard-stop token spending limits and financial budget enforcement per project or agent.',
  tenant_mesh: 'Enterprise mesh topology for cross-tenant collaboration with role-based access.',
  zk_proof: 'Zero-knowledge proof generation for private compliance and verifiable assertions.',
  anomaly: 'Statistical runtime behavior anomaly detection against learned baselines.',
  prompt_optimizer: 'Prompt optimization engine: few-shot selection, chain-of-thought, and DPO tuning.',
  code_index: 'Semantic code indexing with chunking strategies for RAG and symbol search.',
  code_transform: 'Automated code transformations: rename, extract, inline, and migration rewrites.',
  consensus_vote: 'Multi-agent consensus engine with majority, weighted, unanimous, and Borda count strategies.',
  eval_suite: 'Evaluation harness for benchmarking accuracy, speed, safety, robustness, and token efficiency.',
  event_mesh: 'Pub/sub event mesh for streaming state changes, task updates, and agent broadcasts.',
  memory_mesh: 'Distributed memory mesh with CRDT-backed cross-node knowledge sharing.',
  collaboration: 'Real-time multi-user collaboration with OT/CRDT merge, presence, and branching.',
  bridge: 'Protocol bridge converting between OpenAPI, GraphQL, gRPC, and AsyncAPI specifications.',
  did_identity: 'W3C DID-based agent identity with anchor receipts and verifiable credentials.',
  p2p: 'Decentralized peer-to-peer swarm coordination without central servers.',
  tenant: 'Multi-tenant workspace isolation with vault segregation and policy scoping.',
  governance: 'Policy ballot voting and quorum-based governance engine for autonomous decision-making.',
  domain_trust: 'Cross-domain trust anchor for bootstrapping trust between federated workspaces.',
  resilience: 'Fault-tolerant execution policies: circuit breakers, retries, timeouts, and fallbacks.',
};
