import {
  FiEdit3,
  FiTerminal,
  FiUsers,
  FiCpu,
  FiUserPlus,
  FiPackage,
  FiActivity,
  FiRefreshCcw,
  FiSettings,
  FiGitBranch,
  FiSearch,
  FiShoppingBag,
  FiLock,
  FiGlobe,
  FiDroplet,
  FiZap,
  FiAlertOctagon,
  FiMonitor,
  FiAlertTriangle,
  FiFlag,
  FiPlayCircle,
  FiHardDrive,
  FiShield,
  FiFileText,
  FiFolderPlus,
  FiSave,
  FiTrash2,
  FiCode,
  FiGitMerge,
  FiStar,
  FiPlay,
  FiSquare,
  FiShare2,
  FiSidebar,
  FiChevronRight,
  FiChevronDown,
  FiX,
  FiPlus,
  FiFilePlus,
  FiCheck,
  FiXCircle,
  FiRefreshCw,
  FiCircle,
  FiMenu,
  FiMoreVertical,
  FiHelpCircle,
  FiInfo,
  FiDatabase,
  FiBox,
  FiTool,
  FiLayers,
  FiBarChart2,
  FiClock,
  FiUpload,
  FiDownload,
  FiTrash,
  FiEdit,
  FiCopy,
  FiClipboard,
  FiBookmark,
  FiTag,
  FiFilter,
  FiArrowUp,
  FiArrowDown,
  FiArrowLeft,
  FiArrowRight,
  FiExternalLink,
  FiLink,
  FiLink2,
  FiPower,
  FiWifi,
  FiWifiOff,
  FiBluetooth,
  FiToggleLeft,
  FiToggleRight,
  FiMoon,
  FiSun,
  FiCloud,
  FiCloudOff,
  FiKey,
  FiEye,
  FiEyeOff,
  FiBell,
  FiBellOff,
  FiMail,
  FiMicOff,
  FiMessageSquare,
  FiMessageCircle,
  FiPhone,
  FiVideo,
  FiImage,
  FiFilm,
  FiMusic,
  FiHeadphones,
  FiMic,
  FiVolume2,
  FiVolumeX,
  FiSkipBack,
  FiSkipForward,
  FiPause,
  FiMaximize,
  FiMinimize,
  FiScissors,
  FiMove,
  FiCornerUpLeft,
  FiCornerUpRight,
  FiCornerDownLeft,
  FiCornerDownRight,
  FiMaximize2,
  FiMinimize2,
  FiPrinter,
  FiCamera,
  FiMap,
  FiMapPin,
  FiNavigation,
  FiCompass,
  FiSliders,
  FiWind,
  FiThermometer,
  FiUmbrella,
  FiCoffee,
  FiBook,
  FiBookOpen,
  FiFile,
  FiFolder,
  FiArchive,
  FiInbox,
  FiSend,
  FiFastForward,
  FiAtSign,
  FiHash,
  FiPercent,
  FiDollarSign,
} from 'react-icons/fi';

export type IconName = keyof typeof iconMap;

const iconMap = {
  edit: FiEdit3,
  terminal: FiTerminal,
  users: FiUsers,
  cpu: FiCpu,
  userPlus: FiUserPlus,
  puzzle: FiPackage,
  activity: FiActivity,
  bot: FiCpu,
  rotateCcw: FiRefreshCcw,
  settings: FiSettings,
  gitBranch: FiGitBranch,
  search: FiSearch,
  shoppingBag: FiShoppingBag,
  lock: FiLock,
  globe: FiGlobe,
  palette: FiDroplet,
  zap: FiZap,
  bug: FiAlertOctagon,
  monitor: FiMonitor,
  alertTriangle: FiAlertTriangle,
  flag: FiFlag,
  playCircle: FiPlayCircle,
  hardDrive: FiHardDrive,
  shield: FiShield,
  fileText: FiFileText,
  fileCode: FiFileText,
  folderOpen: FiFolderPlus,
  save: FiSave,
  trash2: FiTrash2,
  code: FiCode,
  gitCompare: FiGitMerge,
  star: FiStar,
  play: FiPlay,
  square: FiSquare,
  share2: FiShare2,
  panelLeft: FiSidebar,
  chevronRight: FiChevronRight,
  chevronDown: FiChevronDown,
  x: FiX,
  plus: FiPlus,
  filePlus: FiFilePlus,
  check: FiCheck,
  xCircle: FiXCircle,
  refreshCw: FiRefreshCw,
  circle: FiCircle,
  menu: FiMenu,
  moreVertical: FiMoreVertical,
  helpCircle: FiHelpCircle,
  info: FiInfo,
  alertOctagon: FiAlertOctagon,
  database: FiDatabase,
  box: FiBox,
  tool: FiTool,
  layers: FiLayers,
  network: FiShare2,
  barChart2: FiBarChart2,
  clock: FiClock,
  upload: FiUpload,
  download: FiDownload,
  trash: FiTrash,
  edit2: FiEdit,
  copy: FiCopy,
  clipboard: FiClipboard,
  bookmark: FiBookmark,
  tag: FiTag,
  filter: FiFilter,
  arrowUp: FiArrowUp,
  arrowDown: FiArrowDown,
  arrowLeft: FiArrowLeft,
  arrowRight: FiArrowRight,
  externalLink: FiExternalLink,
  link: FiLink,
  unlink: FiLink2,
  power: FiPower,
  wifi: FiWifi,
  wifiOff: FiWifiOff,
  bluetooth: FiBluetooth,
  toggleLeft: FiToggleLeft,
  toggleRight: FiToggleRight,
  moon: FiMoon,
  sun: FiSun,
  cloud: FiCloud,
  cloudOff: FiCloudOff,
  key: FiKey,
  eye: FiEye,
  eyeOff: FiEyeOff,
  bell: FiBell,
  bellOff: FiBellOff,
  mail: FiMail,
  mailOff: FiMicOff,
  messageSquare: FiMessageSquare,
  messageCircle: FiMessageCircle,
  phone: FiPhone,
  video: FiVideo,
  image: FiImage,
  film: FiFilm,
  music: FiMusic,
  headphones: FiHeadphones,
  mic: FiMic,
  volume2: FiVolume2,
  volumeX: FiVolumeX,
  skipBack: FiSkipBack,
  skipForward: FiSkipForward,
  pause: FiPause,
  maximize: FiMaximize,
  minimize: FiMinimize,
  scissors: FiScissors,
  move: FiMove,
  cornerUpLeft: FiCornerUpLeft,
  cornerUpRight: FiCornerUpRight,
  cornerDownLeft: FiCornerDownLeft,
  cornerDownRight: FiCornerDownRight,
  maximize2: FiMaximize2,
  minimize2: FiMinimize2,
  printer: FiPrinter,
  camera: FiCamera,
  map: FiMap,
  mapPin: FiMapPin,
  navigation: FiNavigation,
  compass: FiCompass,
  wrench: FiTool,
  hammer: FiSettings,
  screwdriver: FiSliders,
  ruler: FiSliders,
  droplet: FiDroplet,
  wind: FiWind,
  thermometer: FiThermometer,
  umbrella: FiUmbrella,
  coffee: FiCoffee,
  book: FiBook,
  bookOpen: FiBookOpen,
  file: FiFile,
  folder: FiFolder,
  archive: FiArchive,
  inbox: FiInbox,
  outbox: FiUpload,
  send: FiSend,
  reply: FiCornerUpLeft,
  forward: FiFastForward,
  atSign: FiAtSign,
  hash: FiHash,
  percent: FiPercent,
  dollarSign: FiDollarSign,
  euro: FiDollarSign,
  poundSterling: FiDollarSign,
  yen: FiDollarSign,
  bitcoin: FiDollarSign,
} as const;

export { iconMap };

export function getIconComponent(name: string): React.ComponentType<{ size?: number; color?: string; className?: string; style?: React.CSSProperties }> {
  return (iconMap[name as IconName] || FiBox) as any;
}
