import {
  FiEdit3,
  FiTerminal,
  FiUsers,
  FiCpu,
  FiUserPlus,
  FiPuzzle,
  FiActivity,
  FiBot,
  FiRefreshCcw,
  FiSettings,
  FiGitBranch,
  FiSearch,
  FiShoppingBag,
  FiLock,
  FiGlobe,
  FiPalette,
  FiZap,
  FiBug,
  FiMonitor,
  FiAlertTriangle,
  FiFlag,
  FiPlayCircle,
  FiHardDrive,
  FiShield,
  FiFileText,
  FiFileCode,
  FiFolderOpen,
  FiSave,
  FiTrash2,
  FiCode,
  FiGitCompare,
  FiStar,
  FiPlay,
  FiSquare,
  FiShare2,
  FiPanelLeft,
  FiChevronRight,
  FiChevronDown,
  FiX,
  FiPlus,
  FiFilePlus,
  FiCheck,
  FiXCircle,
  FiRefreshCw,
  FiCircle,
  FiMenu,
  FiMoreVertical,
  FiHelpCircle,
  FiInfo,
  FiAlertOctagon,
  FiDatabase,
  FiBox,
  FiTool,
  FiLayers,
  FiNetwork,
  FiBarChart2,
  FiClock,
  FiUpload,
  FiDownload,
  FiTrash,
  FiEdit,
  FiCopy,
  FiClipboard,
  FiBookmark,
  FiTag,
  FiFilter,
  FiArrowUp,
  FiArrowDown,
  FiArrowLeft,
  FiArrowRight,
  FiExternalLink,
  FiLink,
  FiUnlink,
  FiPower,
  FiWifi,
  FiWifiOff,
  FiBluetooth,
  FiToggleLeft,
  FiToggleRight,
  FiMoon,
  FiSun,
  FiCloud,
  FiCloudOff,
  FiKey,
  FiEye,
  FiEyeOff,
  FiBell,
  FiBellOff,
  FiMail,
  FiMailOff,
  FiMessageSquare,
  FiMessageCircle,
  FiPhone,
  FiVideo,
  FiImage,
  FiFilm,
  FiMusic,
  FiHeadphones,
  FiMic,
  FiVolume2,
  FiVolumeX,
  FiSkipBack,
  FiSkipForward,
  FiPause,
  FiMaximize,
  FiMinimize,
  FiScissors,
  FiMove,
  FiCornerUpLeft,
  FiCornerUpRight,
  FiCornerDownLeft,
  FiCornerDownRight,
  FiMaximize2,
  FiMinimize2,
  FiPrinter,
  FiCamera,
  FiMap,
  FiMapPin,
  FiNavigation,
  FiCompass,
  FiWrench,
  FiHammer,
  FiScrewdriver,
  FiRuler,
  FiDroplet,
  FiWind,
  FiThermometer,
  FiUmbrella,
  FiCoffee,
  FiBook,
  FiBookOpen,
  FiFile,
  FiFolder,
  FiArchive,
  FiInbox,
  FiOutbox,
  FiSend,
  FiReply,
  FiForward,
  FiAtSign,
  FiHash,
  FiPercent,
  FiDollarSign,
  FiEuro,
  FiPoundSterling,
  FiYen,
  FiBitcoin,
} from 'react-icons/fi';

export type IconName = keyof typeof iconMap;

const iconMap = {
  edit: FiEdit3,
  terminal: FiTerminal,
  users: FiUsers,
  cpu: FiCpu,
  userPlus: FiUserPlus,
  puzzle: FiPuzzle,
  activity: FiActivity,
  bot: FiBot,
  rotateCcw: FiRefreshCcw,
  settings: FiSettings,
  gitBranch: FiGitBranch,
  search: FiSearch,
  shoppingBag: FiShoppingBag,
  lock: FiLock,
  globe: FiGlobe,
  palette: FiPalette,
  zap: FiZap,
  bug: FiBug,
  monitor: FiMonitor,
  alertTriangle: FiAlertTriangle,
  flag: FiFlag,
  playCircle: FiPlayCircle,
  hardDrive: FiHardDrive,
  shield: FiShield,
  fileText: FiFileText,
  fileCode: FiFileCode,
  folderOpen: FiFolderOpen,
  save: FiSave,
  trash2: FiTrash2,
  code: FiCode,
  gitCompare: FiGitCompare,
  star: FiStar,
  play: FiPlay,
  square: FiSquare,
  share2: FiShare2,
  panelLeft: FiPanelLeft,
  chevronRight: FiChevronRight,
  chevronDown: FiChevronDown,
  x: FiX,
  plus: FiPlus,
  filePlus: FiFilePlus,
  check: FiCheck,
  xCircle: FiXCircle,
  refreshCw: FiRefreshCw,
  circle: FiCircle,
  menu: FiMenu,
  moreVertical: FiMoreVertical,
  helpCircle: FiHelpCircle,
  info: FiInfo,
  alertOctagon: FiAlertOctagon,
  database: FiDatabase,
  box: FiBox,
  tool: FiTool,
  layers: FiLayers,
  network: FiNetwork,
  barChart2: FiBarChart2,
  clock: FiClock,
  upload: FiUpload,
  download: FiDownload,
  trash: FiTrash,
  edit2: FiEdit,
  copy: FiCopy,
  clipboard: FiClipboard,
  bookmark: FiBookmark,
  tag: FiTag,
  filter: FiFilter,
  arrowUp: FiArrowUp,
  arrowDown: FiArrowDown,
  arrowLeft: FiArrowLeft,
  arrowRight: FiArrowRight,
  externalLink: FiExternalLink,
  link: FiLink,
  unlink: FiUnlink,
  power: FiPower,
  wifi: FiWifi,
  wifiOff: FiWifiOff,
  bluetooth: FiBluetooth,
  toggleLeft: FiToggleLeft,
  toggleRight: FiToggleRight,
  moon: FiMoon,
  sun: FiSun,
  cloud: FiCloud,
  cloudOff: FiCloudOff,
  key: FiKey,
  eye: FiEye,
  eyeOff: FiEyeOff,
  bell: FiBell,
  bellOff: FiBellOff,
  mail: FiMail,
  mailOff: FiMailOff,
  messageSquare: FiMessageSquare,
  messageCircle: FiMessageCircle,
  phone: FiPhone,
  video: FiVideo,
  image: FiImage,
  film: FiFilm,
  music: FiMusic,
  headphones: FiHeadphones,
  mic: FiMic,
  volume2: FiVolume2,
  volumeX: FiVolumeX,
  skipBack: FiSkipBack,
  skipForward: FiSkipForward,
  pause: FiPause,
  maximize: FiMaximize,
  minimize: FiMinimize,
  scissors: FiScissors,
  move: FiMove,
  cornerUpLeft: FiCornerUpLeft,
  cornerUpRight: FiCornerUpRight,
  cornerDownLeft: FiCornerDownLeft,
  cornerDownRight: FiCornerDownRight,
  maximize2: FiMaximize2,
  minimize2: FiMinimize2,
  printer: FiPrinter,
  camera: FiCamera,
  map: FiMap,
  mapPin: FiMapPin,
  navigation: FiNavigation,
  compass: FiCompass,
  wrench: FiWrench,
  hammer: FiHammer,
  screwdriver: FiScrewdriver,
  ruler: FiRuler,
  droplet: FiDroplet,
  wind: FiWind,
  thermometer: FiThermometer,
  umbrella: FiUmbrella,
  coffee: FiCoffee,
  book: FiBook,
  bookOpen: FiBookOpen,
  file: FiFile,
  folder: FiFolder,
  archive: FiArchive,
  inbox: FiInbox,
  outbox: FiOutbox,
  send: FiSend,
  reply: FiReply,
  forward: FiForward,
  atSign: FiAtSign,
  hash: FiHash,
  percent: FiPercent,
  dollarSign: FiDollarSign,
  euro: FiEuro,
  poundSterling: FiPoundSterling,
  yen: FiYen,
  bitcoin: FiBitcoin,
} as const;

export { iconMap };

export function getIconComponent(name: string): React.ComponentType<{ size?: number; color?: string; className?: string }> {
  return iconMap[name as IconName] || FiBox;
}
