# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hydra_pb2 as hydra__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hydra_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HydraDaemonStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunGoal = channel.unary_unary(
                '/hydra.HydraDaemon/RunGoal',
                request_serializer=hydra__pb2.TaskCreated.SerializeToString,
                response_deserializer=hydra__pb2.TaskStarted.FromString,
                _registered_method=True)
        self.StreamEvents = channel.stream_stream(
                '/hydra.HydraDaemon/StreamEvents',
                request_serializer=hydra__pb2.Event.SerializeToString,
                response_deserializer=hydra__pb2.Event.FromString,
                _registered_method=True)
        self.Generate = channel.unary_unary(
                '/hydra.HydraDaemon/Generate',
                request_serializer=hydra__pb2.InferenceRequest.SerializeToString,
                response_deserializer=hydra__pb2.InferenceResponse.FromString,
                _registered_method=True)


class HydraDaemonServicer:
    """Missing associated documentation comment in .proto file."""

    def RunGoal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HydraDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.RunGoal,
                    request_deserializer=hydra__pb2.TaskCreated.FromString,
                    response_serializer=hydra__pb2.TaskStarted.SerializeToString,
            ),
            'StreamEvents': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=hydra__pb2.Event.FromString,
                    response_serializer=hydra__pb2.Event.SerializeToString,
            ),
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=hydra__pb2.InferenceRequest.FromString,
                    response_serializer=hydra__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra.HydraDaemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydra.HydraDaemon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HydraDaemon:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra.HydraDaemon/RunGoal',
            hydra__pb2.TaskCreated.SerializeToString,
            hydra__pb2.TaskStarted.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hydra.HydraDaemon/StreamEvents',
            hydra__pb2.Event.SerializeToString,
            hydra__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydra.HydraDaemon/Generate',
            hydra__pb2.InferenceRequest.SerializeToString,
            hydra__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
