[package]
name = "hydra-browser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "hydra_browser"
path = "src/lib.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tokio.workspace = true
async-trait = "0.1"
chrono = "0.4"
hydra-tools = { path = "../hydra-tools" }
