import { AlpObject } from '@autonomous-lifecycle-protocol-alp/parser';

export function buildContextBundle(
  task: AlpObject,
  project: AlpObject | null,
  agent: AlpObject | null,
  memories: AlpObject[],
  rules: AlpObject[],
  decisions: AlpObject[],
  allObjects: AlpObject[]
): string {
  const sections: string[] = [];

  sections.push('# ALP Task Execution Context');
  sections.push(`Generated by \`alp run\` at ${new Date().toISOString()}\n`);

  if (project) {
    sections.push('## Project');
    sections.push(`- Name: ${project.id || 'unnamed'}`);
    if (project.description) sections.push(`- Description: ${project.description}`);
    if (project.stack) sections.push(`- Stack: ${project.stack}`);
    sections.push('');
  }

  sections.push('## Target Task');
  sections.push(`- ID: ${task.id}`);
  if (task.description) sections.push(`- Description: ${task.description}`);
  if (task.priority) sections.push(`- Priority: ${task.priority}`);
  if (task.status) sections.push(`- Status: ${task.status}`);
  sections.push('');

  if (task.accept && Array.isArray(task.accept)) {
    sections.push('## Acceptance Criteria');
    for (const criterion of task.accept) {
      sections.push(`- ${criterion}`);
    }
    sections.push('');
  }

  if (task.verify && Array.isArray(task.verify)) {
    sections.push('## Verification Commands');
    for (const step of task.verify) {
      sections.push(`- \`${step}\``);
    }
    sections.push('');
  }

  if (agent) {
    sections.push('## Assigned Agent');
    sections.push(`- Role: ${agent.id}`);
    if (agent.description) sections.push(`- Description: ${agent.description}`);
    if (agent.capabilities && Array.isArray(agent.capabilities)) {
      sections.push(`- Capabilities: ${agent.capabilities.join(', ')}`);
    }
    sections.push('');
  }

  if (rules.length > 0) {
    sections.push('## Architectural Rules (MUST follow)');
    for (const rule of rules) {
      sections.push(`- **${rule.id}**: ${rule.description || rule.enforce || 'N/A'}`);
    }
    sections.push('');
  }

  if (decisions.length > 0) {
    sections.push('## Finalized Decisions');
    for (const dec of decisions) {
      sections.push(`- **${dec.id}**: ${dec.description || dec.outcome || 'N/A'}`);
    }
    sections.push('');
  }

  if (memories.length > 0) {
    sections.push('## Relevant Memories');
    for (const mem of memories) {
      sections.push(`- **${mem.id}** (${mem.type || 'general'}): ${mem.description || mem.content || 'N/A'}`);
    }
    sections.push('');
  }

  return sections.join('\n');
}
