/**
 * Base generator abstract class for ALP code generation.
 * Provides common utilities for all target language generators.
 */

export interface CodegenOptions {
  target: 'php' | 'cpp' | 'typescript';
  namespace?: string;
  outputDir?: string;
  indent?: string;
  header?: boolean;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export abstract class BaseGenerator {
  protected options: Required<CodegenOptions>;

  constructor(options: CodegenOptions) {
    this.options = {
      target: options.target,
      namespace: options.namespace || 'App',
      outputDir: options.outputDir || './out',
      indent: options.indent || '    ',
      header: options.header !== false,
    };
  }

  /** Sanitize an ALP identifier for the target language */
  protected sanitizeId(id: string): string {
    return id.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[0-9]/, '_$&');
  }

  /** Escape a string literal for the target language */
  protected escapeString(value: string): string {
    return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/"/g, '\\"');
  }

  /** Generate header comment block */
  protected generateHeader(className: string): string {
    if (!this.options.header) return '';
    const now = new Date().toISOString();
    return `/**
 * Auto-generated by ALP CodeGen (${this.options.target})
 * Generated at: ${now}
 * Class: ${className}
 */\n\n`;
  }

  /** Convert ALP type to target language type */
  protected mapType(alpType: string): string {
    const typeMap: Record<string, string> = {
      task: 'Task',
      agent: 'Agent',
      feature: 'Feature',
      workflow: 'Workflow',
      policy: 'Policy',
      contract: 'Contract',
      vault: 'Vault',
      rule: 'Rule',
      timeline: 'Timeline',
      memory: 'Memory',
      swarm: 'Swarm',
      tenant: 'Tenant',
      project: 'Project',
      multimodal: 'Multimodal',
      vision_model: 'VisionModel',
      action_space: 'ActionSpace',
    };
    return typeMap[alpType] || this.sanitizeId(alpType);
  }

  /** Convert ALP status marker to target language constant value */
  protected mapStatus(status: string): string {
    const map: Record<string, string> = {
      '[ ]': 'PENDING',
      '[x]': 'DONE',
      '[~]': 'IN_PROGRESS',
      '[!]': 'BLOCKED',
      '[?]': 'REVIEW',
    };
    return map[status] || 'UNKNOWN';
  }

  /** Indent a block of code */
  protected indentBlock(code: string, levels: number = 1): string {
    const prefix = this.options.indent.repeat(levels);
    return code
      .split('\n')
      .map((line) => (line.trim() === '' ? line : prefix + line))
      .join('\n');
  }

  /** Generate a namespace/package declaration */
  protected abstract generateNamespace(): string;

  /** Generate imports/requires for a class */
  protected abstract generateImports(imports: string[]): string;

  /** Generate class declaration */
  protected abstract generateClassDeclaration(className: string, interfaces: string[]): string;

  /** Generate class footer */
  protected abstract generateClassFooter(): string;

  /** Generate a property/field declaration */
  protected abstract generateProperty(name: string, type: string, value?: string): string;

  /** Generate a method declaration */
  protected abstract generateMethod(name: string, params: string[], body: string): string;

  /** Generate a constant declaration */
  protected abstract generateConstant(name: string, value: string): string;

  /** Main entry point — generate all files from ALP objects */
  abstract generate(objects: Record<string, any>[]): GeneratedFile[];
}
